site_name: 'python-app'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/lucas-flx/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'